name: Android - Build & Deploy to Google Play Closed-Testing

on:
  push:
    branches:
      - 'staging@android'
    paths:
      - 'android/**'
      - 'app/**'
      - 'components/**'
      - 'assets/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/android/app/release.keystore
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID }}
      FIREBASE_GOOGLE_KEY: ${{ secrets.FIREBASE_GOOGLE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}" > .env

      - name: Create firebase google-services.json
        run: |
          echo "${{ env.FIREBASE_GOOGLE_KEY }}" > android/app/google-services.json

      - name: Install npm dependencies
        run: npm ci

      - name: Decode and save keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ${{ env.ANDROID_KEYSTORE_FILE }}
          chmod 600 ${{ env.ANDROID_KEYSTORE_FILE }}

      - name: Install Fastlane dependencies
        working-directory: android
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build and deploy to Google Play (Closed Testing)
        working-directory: android
        run: bundle exec fastlane closed_testing

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-build-artifacts
          path: |
            android/app/build/outputs/bundle/release/*.aab
            android/app/build/outputs/mapping/release/mapping.txt
          retention-days: 30

      - name: Clean up keystore
        if: always()
        run: rm -f ${{ env.ANDROID_KEYSTORE_FILE }}
